### ISSUE TITLE
Team Users break User Lookup Interface

### ISSUE THREAD

**Issue by grifgrif** [fbrettnich/DiscordLookup#22]
Looking up Team Users break the User Lookup Interface.
![BugImage](https://i.discord.fr/Wova.png)

**Comment by grifgrif** [comment]
(Also, I have no idea how to add labels.)

**Comment by fbrettnich** [comment]
Fixed

![image](https://user-images.githubusercontent.com/42101045/194037770-d7ad3a76-9f3a-413e-b97f-b78d8a5abc6b.png)
